
# 도서 쇼핑몰 프로젝트 테이블 생성 sql

# 생성 예상 테이블
# 1. 회원정보 테이블 SHOP_MEMBER
# 2. 도서 카테고리 테이블 BOOK_CATEGORY
# 3. 도서 정보 테이블 SHOP_BOOK
# 4. 장바구니 테이블 SHOP_CART
# 5. 구매정보 테이블 SHOP_BUY


# 회원 정보 테이블 생성
CREATE TABLE SHOP_MEMBER(
	MEM_EMAIL VARCHAR(50) PRIMARY KEY
	, MEM_PW VARCHAR(50) NOT NULL 
	, MEM_NAME VARCHAR(30) NOT NULL 
	, MEM_TEL VARCHAR(15) NOT NULL UNIQUE # 010-1111-2222
	, MEM_ADDR VARCHAR(50)
	, ADDR_DETAIL VARCHAR(100)
	, IS_USING VARCHAR(10) DEFAULT 'Y' #'Y' : 사용중 , 'N' : 휴면계정
	, MEM_ROLE VARCHAR(20) DEFAULT 'USER' # 회원 권한 : 'USER' - 일반회원, 'MANAGER' - 쇼핑몰 운영자, 'ADMIN' - 관리자
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM shop_member;

UPDATE SHOP_MEMBER 
   SET 
   	MEM_EMAIL = 'manager'
   	, MEM_PW = '1111'
   	, MEM_ROLE = 'MANAGER'
 WHERE MEM_EMAIL = '111';

# 도서 카테고리 테이블
CREATE TABLE BOOK_CATEGORY(
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CATE_NAME VARCHAR(20) NOT NULL UNIQUE
);

SELECT * FROM BOOK_CATEGORY;

# 카테고리 기본 데이터
INSERT INTO BOOK_CATEGORY VALUES(1, 'IT/인터넷');
INSERT INTO BOOK_CATEGORY VALUES(2, '자기계발');
INSERT INTO BOOK_CATEGORY VALUES(3, '소설/에세이');

# 도서정보 테이블
CREATE TABLE SHOP_BOOK(
	BOOK_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BOOK_TITLE VARCHAR(30) NOT NULL 
	, AUTHOR VARCHAR(20) NOT NULL 
	, BOOK_PRICE INT NOT NULL 
	, BOOK_STOCK INT DEFAULT 10
	, BOOK_INTRO VARCHAR(50)
	, PUBLISH_DATE DATETIME #출판일
	, CATE_NUM INT NOT NULL REFERENCES BOOK_CATEGORY (CATE_NUM)
);

# 도서 이미지 정보 테이블
CREATE TABLE BOOK_IMG(
	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_FILE_NAME VARCHAR(100) 		#원본 파일명
	, UPROAD_FILE_NAME VARCHAR(100) 		#첨부 파일명
	, IS_MAIN VARCHAR(1) NOT NULL 		 	#대표 이미지 여부('Y', 'N')
	, BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) ON DELETE CASCADE
);

SELECT * FROM SHOP_BOOK;
SELECT * FROM BOOK_IMG;

# DELETE FROM SHOP_BOOK;

INSERT INTO BOOK_IMG (
	ORIGIN_FILE_NAME
	, UPROAD_FILE_NAME
	, IS_MAIN
	, BOOK_NUM
) 
VALUES
(#{}, #{}, #{}, #{}),
(#{}, #{}, #{}, #{}),
(#{}, #{}, #{}, #{});

# DELETE FROM BOOK_IMG;

# 테이블에 저장된 가장 큰 도서번호 + 1 데이터를 조회
SELECT IFNULL(MAX(BOOK_NUM), 0) + 1 AS 최대글번호
  FROM SHOP_BOOK;

 

