
# 도서 쇼핑몰 프로젝트 테이블 생성 sql

# 생성 예상 테이블
# 1. 회원정보 테이블 SHOP_MEMBER
# 2. 도서 카테고리 테이블 BOOK_CATEGORY
# 3. 도서 정보 테이블 SHOP_BOOK
# 4. 장바구니 테이블 SHOP_CART
# 5. 구매정보 테이블 SHOP_BUY


# 회원 정보 테이블 생성
CREATE TABLE SHOP_MEMBER(
	MEM_EMAIL VARCHAR(50) PRIMARY KEY
	, MEM_PW VARCHAR(50) NOT NULL 
	, MEM_NAME VARCHAR(30) NOT NULL 
	, MEM_TEL VARCHAR(15) NOT NULL UNIQUE # 010-1111-2222
	, MEM_ADDR VARCHAR(50)
	, ADDR_DETAIL VARCHAR(100)
	, IS_USING VARCHAR(10) DEFAULT 'Y' #'Y' : 사용중 , 'N' : 휴면계정
	, MEM_ROLE VARCHAR(20) DEFAULT 'USER' # 회원 권한 : 'USER' - 일반회원, 'MANAGER' - 쇼핑몰 운영자, 'ADMIN' - 관리자
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM shop_member;

UPDATE SHOP_MEMBER 
   SET 
   	MEM_EMAIL = 'manager'
   	, MEM_PW = '1111'
   	, MEM_ROLE = 'MANAGER'
 WHERE MEM_EMAIL = '111';

# 도서 카테고리 테이블
CREATE TABLE BOOK_CATEGORY(
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CATE_NAME VARCHAR(20) NOT NULL UNIQUE
);

SELECT * FROM BOOK_CATEGORY;

# 카테고리 기본 데이터
INSERT INTO BOOK_CATEGORY VALUES(1, 'IT/인터넷');
INSERT INTO BOOK_CATEGORY VALUES(2, '자기계발');
INSERT INTO BOOK_CATEGORY VALUES(3, '소설/에세이');

# 도서정보 테이블
CREATE TABLE SHOP_BOOK(
	BOOK_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BOOK_TITLE VARCHAR(30) NOT NULL 
	, AUTHOR VARCHAR(20) NOT NULL 
	, BOOK_PRICE INT NOT NULL 
	, BOOK_STOCK INT DEFAULT 10
	, BOOK_INTRO VARCHAR(50)
	, PUBLISH_DATE DATETIME #출판일
	, CATE_NUM INT NOT NULL REFERENCES BOOK_CATEGORY (CATE_NUM)
);

# 도서 이미지 정보 테이블
CREATE TABLE BOOK_IMG(
	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_FILE_NAME VARCHAR(100) 		#원본 파일명
	, UPROAD_FILE_NAME VARCHAR(100) 		#첨부 파일명
	, IS_MAIN VARCHAR(1) NOT NULL 		 	#대표 이미지 여부('Y', 'N')
	, BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) ON DELETE CASCADE
);

SELECT * FROM SHOP_BOOK;
SELECT * FROM BOOK_IMG;

# DELETE FROM SHOP_BOOK;

INSERT INTO BOOK_IMG (
	ORIGIN_FILE_NAME
	, UPROAD_FILE_NAME
	, IS_MAIN
	, BOOK_NUM
) 
VALUES
(#{}, #{}, #{}, #{}),
(#{}, #{}, #{}, #{}),
(#{}, #{}, #{}, #{});

# DELETE FROM BOOK_IMG;

# 테이블에 저장된 가장 큰 도서번호 + 1 데이터를 조회
SELECT IFNULL(MAX(BOOK_NUM), 0) + 1 AS 최대글번호
  FROM SHOP_BOOK;

# 도서번호, 도서명, 도서가격, 해당 도서의 첨부된 파일 조회
#SELECT S.BOOK_NUM, BOOK_TITLE, BOOK_PRICE, UPROAD_FILE_NAME
  #FROM SHOP_BOOK S INNER JOIN BOOK_IMG I
    #ON S.BOOK_NUM = I.BOOK_NUM
 #WHERE IS_MAIN = 'Y';

 SELECT S.BOOK_NUM, BOOK_TITLE, BOOK_PRICE, UPROAD_FILE_NAME
   FROM SHOP_BOOK S, BOOK_IMG I
  WHERE S.BOOK_NUM = I.BOOK_NUM;
    AND IS_MAIN = 'Y';
 
 # 도서번호, 도서명, 도서가격, 수량, 총 구매가격, 해당 도서의 첨부된 파일 조회
# SELECT S.BOOK_NUM
            , BOOK_TITLE
            , BOOK_PRICE
            , BOOK_STOCK
            , IS_MAIN
            , UPROAD_FILE_NAME
  #FROM SHOP_BOOK S, BOOK_IMG I
  #WHERE S.BOOK_NUM = I.BOOK_NUM
  	#AND S.BOOK_NUM = 1;
 
            
# 장바구니 정보 테이블
CREATE TABLE SHOP_CART(
	CART_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) 
	, CART_CNT INT NOT NULL
	, MEM_EMAIL VARCHAR(50) NOT NULL REFERENCES SHOP_MEMBER (MEM_EMAIL)
	, CART_DATE DATETIME DEFAULT SYSDATE()
); 

SELECT * FROM SHOP_CART;

SELECT B.BOOK_NUM, BOOK_TITLE, BOOK_PRICE, UPROAD_FILE_NAME, I.IS_MAIN
  FROM SHOP_BOOK B, BOOK_IMG I
  WHERE B.BOOK_NUM = I.BOOK_NUM;

SELECT B.BOOK_NUM, BOOK_PRICE, CART_CNT, CART_DATE
  FROM SHOP_BOOK B, SHOP_CART C
  WHERE B.BOOK_NUM = C.BOOK_NUM
    AND C.MEM_EMAIL = #{memEmail}
    
    SELECT B.BOOK_NUM
            , UPROAD_FILE_NAME
            , BOOK_TITLE
            , BOOK_PRICE
            , CART_CNT
            , CART_DATE
            , IS_MAIN
        FROM 
        SHOP_BOOK B INNER JOIN BOOK_IMG I INNER JOIN SHOP_CART C
        WHERE B.BOOK_NUM = C.BOOK_NUM
        AND C.MEM_EMAIL #{memEmail}
        AND IS_MAIN = 'Y';
    
    SELECT B.BOOK_NUM
            , UPROAD_FILE_NAME
            , BOOK_TITLE
            , BOOK_PRICE
            , CART_CNT
            , CART_DATE
            , IS_MAIN
        FROM SHOP_BOOK B INNER JOIN SHOP_CART C
        ON B.BOOK_NUM = C.BOOK_NUM
        WHERE C.MEM_EMAIL  #{memEmail}
        AND IS_MAIN = 'Y';
    
    MERGE INTO SHOP_BOOK B
    USING SHOP_CART C
       ON B.BOOK_NUM = C.BOOK_NUM
     WHEN MATCHED THEN
     	UPDATE SET CART_CNT = + #{cartCnt}
     WHEN MATCHED THEN
     	INSERT (BOOK_NUM
     		, CART_CNT
     		, MEM_EAMIL) 
     		VALUES(
     			#{bookNum}
     			, #{cartCnt}
     			, #{memEmail}
     		);
    
    SELECT * FROM SHOP_BOOK 
    
    #DELETE FROM SHOP_CART;
    
# 구매 정보 테이블
CREATE TABLE SHOP_BUY(
	BUY_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BUY_PRICE INT NOT NULL					# 총 구매 금액
	, MEM_EMAIL VARCHAR(50) NOT NULL REFERENCES SHOP_MEMBER (MEM_EMAIL)
	, BUY_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM SHOP_BUY;

# 구매 상세 정보 테이블
CREATE TABLE BUY_DETAIL(
	BUY_DETAIL_NUM INT PRIMARY KEY AUTO_INCREMENT 				# 구매 상세 번호
	, BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) 	# 도서 번호
	, BUY_CNT INT NOT NULL										# 구매 수량
	, BUY_NUM INT NOT NULL REFERENCES SHOP_BUY (BUY_NUM)		# 구매 번호
);

SELECT * FROM BUY_DETAIL;

#INSERT INTO SHOP_BUY VALUES(1, 50000, 'aaa', SYSDATE());
#INSERT INTO BUY_DETAIL VALUES(1, 4, 1, 1);
#INSERT INTO BUY_DETAIL VALUES(2, 1, 2, 1);

#INSERT INTO SHOP_BUY VALUES(2, 100000, 'aaa', SYSDATE());
#INSERT INTO BUY_DETAIL VALUES(3, 3, 1, 2);
#INSERT INTO BUY_DETAIL VALUES(4, 2, 1, 2);
#INSERT INTO BUY_DETAIL VALUES(5, 5, 1, 2);

#DELETE FROM SHOP_BUY;
#DELETE FROM buy_detail;

# 구매할 도서명, 총 구매 금액, 구매 날짜, 도서 가격, 구매 수량, 도서별 구매 가격, 이미지명
SELECT B.BUY_NUM
	, BUY_PRICE #총 구매 금액
	, BUY_DATE  #구매 일시
	, BUY_CNT   #구매 수량
	, BOOK_TITLE #구매할 도서명 
	, BOOK_PRICE #도서별 구매 가격
	, UPROAD_FILE_NAME #이미지명
  FROM SHOP_BUY B 
 INNER JOIN BUY_DETAIL D
    ON B.BUY_NUM = D.BUY_NUM
 INNER JOIN SHOP_BOOK BOOK
    ON D.BOOK_NUM = BOOK.BOOK_NUM
 INNER JOIN BOOK_IMG I
    ON I.BOOK_NUM = BOOK.BOOK_NUM
 WHERE IS_MAIN = 'Y'
   AND MEM_EMAIL = 'aaa'
 ORDER BY BUY_DATE DESC;

SELECT * FROM SHOP_BUY;
SELECT * FROM BUY_DETAIL;

# 오늘의 매출금액 조회
SELECT BUY_NUM 
	, BUY_PRICE
	, BUY_DATE
  FROM SHOP_BUY 
HAVING DATE(BUY_DATE) = '2026-03-04';

SELECT SYSDATE();

# 오늘의 주문건수 + 오늘의 매출 총 액 조회
SELECT COUNT(BUY_NUM)
	, SUM(BUY_PRICE)
  FROM  SHOP_BUY 
WHERE DATE(BUY_DATE) = CURRENT_DATE();

# 오늘의 주문건수
SELECT COUNT(BUY_NUM)
  FROM  SHOP_BUY 
WHERE DATE(BUY_DATE) = CURRENT_DATE();

# 이달의 주문건수 조회
# 이번달의 1일부터 오늘까지
SELECT COUNT(BUY_NUM)
  FROM  SHOP_BUY 
WHERE DATE(BUY_DATE) 
BETWEEN CONCAT(TO_CHAR(CURRENT_DATE(), 'YYYY-MM'), '-01')
  AND CURRENT_DATE();

SELECT BUY_DATE
	, CONCAT(TO_CHAR(CURRENT_DATE(), 'YYYY-MM'), '-01')
  FROM SHOP_BUY;

SELECT 
	(
		SELECT COUNT(BUY_NUM)
  		  FROM  SHOP_BUY 
		 WHERE DATE(BUY_DATE) = CURRENT_DATE()
	) AS SALE_CNT_TODAY, 
	(
		SELECT COUNT(BUY_NUM)
  		  FROM  SHOP_BUY 
		 WHERE DATE(BUY_DATE) 
 	   BETWEEN CONCAT(TO_CHAR(CURRENT_DATE(), 'YYYY-MM'), '-01')
  		   AND CURRENT_DATE()
	) AS SALE_CNT_MONTH,(
		SELECT NVL(SUM(BUY_PRICE), 0)
 		  FROM SHOP_BUY
 		 WHERE DATE(BUY_DATE) = CURRENT_DATE()
	) AS SALE_TODAY, (
		SELECT NVL(SUM(BUY_PRICE), 0)
  		  FROM SHOP_BUY
 		 WHERE DATE(BUY_DATE) 
 	   BETWEEN CONCAT(TO_CHAR(CURRENT_DATE(), 'YYYY-MM'), '-01')
   		   AND CURRENT_DATE()
	) AS SALE_MONTH;

# 오늘의 매출 금액
SELECT SUM(BUY_PRICE)
  FROM SHOP_BUY
 WHERE DATE(BUY_DATE) = CURRENT_DATE();

# 이달의 매출 금액
SELECT SUM(BUY_PRICE)
  FROM SHOP_BUY
 WHERE DATE(BUY_DATE) BETWEEN CONCAT(TO_CHAR(CURRENT_DATE(), 'YYYY-MM'), '-01')
   AND CURRENT_DATE()
   
# 연봉 최상위 3명 조회
 SELECT EMPNO, ENAME, SAL
   FROM EMP 
  ORDER BY SAL DESC
  LIMIT 3 OFFSET 0;
# OFFSET + 숫자: OFFSET은 숫자의 개수변수큼 건너뛰고 조회하겠다

# 구매랭킹
SELECT MEM_EMAIL
	, SUM(BUY_PRICE) SALE_PER_MEMBER
	, COUNT(BUY_NUM) SALE_CNT_PER_MEMBER
	, ROW_NUMBER() OVER(ORDER BY SALE_PER_MEMBER DESC) RANK
  FROM SHOP_BUY
 GROUP BY MEM_EMAIL
 ORDER BY SALE_PER_MEMBER DESC
 LIMIT 5;

SELECT * FROM SHOP_BOOK;
SELECT * FROM BUY_DETAIL;
SELECT * FROM SHOP_BUY;

# 인기랭킹
SELECT D.BOOK_NUM, SUM(BUY_CNT) TOTAL_CNT, BOOK_TITLE, AUTHOR
  FROM BUY_DETAIL D INNER JOIN SHOP_BOOK B
    ON D.BOOK_NUM = B.BOOK_NUM
 GROUP BY D.BOOK_NUM
 ORDER BY SUM(BUY_CNT) DESC
 LIMIT 5;

SELECT D.BOOK_NUM, SUM(BUY_CNT) TOTAL_BUY_CNT, BOOK_TITLE, AUTHOR
  FROM BUY_DETAIL D, SHOP_BOOK B
 WHERE D.BOOK_NUM = B.BOOK_NUM 
 GROUP BY D.BOOK_NUM
 ORDER BY TOTAL_BUY_CNT DESC, BOOK_TITLE 
 LIMIT 5;

SELECT BOOK_NUM
	, SUM(BUY_CNT)
	,(SELECT BOOK_TITLE
	 	FROM SHOP_BOOK
	   WHERE BOOK_NUM = BUY_DETAIL.BOOK_NUM) AS BOOK_TITLE
	,(SELECT AUTHOR
	 	FROM SHOP_BOOK
	   WHERE BOOK_NUM = BUY_DETAIL.BOOK_NUM) AS AUTHOR
  FROM BUY_DETAIL 
 GROUP BY BOOK_NUM;
 
# 최근 10일간의 날짜를 조회
# UNION ALL : 서로 다른 SELECT결과를 병합하는 것(중복 결과도 포함)
SELECT CURRENT_DATE(), SUM(BUY_PRICE)
  FROM SHOP_BUY
 WHERE DATE(BUY_DATE)
  
SELECT 1, 2
UNION
SELECT 3, 4;

SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE JOB = '사원'
UNION ALL
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE JOB = '과장';

############################# 차트 조회 쿼리 ########################################## 
#current_date(), -9

SELECT ADDDATE(CURRENT_DATE(), -3) BUY_DATE,
	(SELECT NVL(SUM(BUY_PRICE),0)
		 FROM SHOP_BUY
		 WHERE DATE(BUY_DATE) = ADDDATE(CURRENT_DATE(), -3)) AS SALE
UNION ALL
SELECT ADDDATE(CURRENT_DATE(), -2),
	(SELECT NVL(SUM(BUY_PRICE),0)
		 FROM SHOP_BUY
		 WHERE DATE(BUY_DATE) = ADDDATE(CURRENT_DATE(), -2)) AS SALE
UNION ALL
SELECT ADDDATE(CURRENT_DATE(), -1), 
	(SELECT NVL(SUM(BUY_PRICE),0)
		 FROM SHOP_BUY
		 WHERE DATE(BUY_DATE) = ADDDATE(CURRENT_DATE(), -1)) AS SALE
UNION ALL
SELECT ADDDATE(CURRENT_DATE(), -0),
	(SELECT NVL(SUM(BUY_PRICE), 0)
		 FROM SHOP_BUY
		 WHERE DATE(BUY_DATE) = ADDDATE(CURRENT_DATE(), -0)) AS SALE;

####################################################################################
SELECT CURRENT_DATE()
	, (SELECT SUM(BUY_PRICE)
		 FROM SHOP_BUY
		 WHERE DATE(BUY_DATE) = CURRENT_DATE()) AS SALE;





